export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_IN_START = 'SIGN_IN_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';

export const SENDER_INFO_SUCCESS = 'SENDER_INFO_SUCCESS';
export const SENDER_INFO_FAIL = 'SENDER_INFO_FAIL';

export const RECEIVER_INFO_SUCCESS = 'RECEIVER_INFO_SUCCESS';
export const RECEIVER_INFO_FAIL = 'RECEIVER_INFO_FAIL';

export const SET_RECEIVER_LOADING = 'SET_RECEIVER_LOADING';
export const SET_SENDER_LOADING = 'SET_SENDER_LOADING';

export const SET_LOADING_AUTH = 'SET_LOADING_AUTH';
export const NOT_LOADING_AUTH = 'NOT_LOADING_AUTH';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
